#!/bin/sh -e

# Adminer Nginx Confg Script

# Link conf file to available-sites, and enable it
ln -s /etc/adminer/nginx.conf /etc/nginx/sites-available/adminer
ln -s /etc/nginx/sites-available/adminer /etc/nginx/sites-enabled/adminer

