#!/bin/bash -ex

# Set variables
USER=mayan
APP_NAME=mayan-edms
APP_DIR=/opt/$APP_NAME
BIN=$APP_DIR/bin
DB_NAME=$USER
DB_USER=$USER
DB_PASS=$(mcookie)
RE_PASS=$(mcookie)
SV_CONF=/etc/supervisor/conf.d/$USER.conf
ENV_CONF=/etc/$USER/env

adduser $USER --disabled-password --disabled-login --no-create-home --gecos ""

mkdir -p $APP_DIR
virtualenv -p /usr/bin/python3 $APP_DIR
chown -R $USER:$USER $APP_DIR
mkdir -p /var/log/$USER
chown -R $USER:$USER /var/log/$USER

# create convenience env dirs file
mkdir -p $(dirname $ENV_CONF)
cat > $ENV_CONF <<EOF
export MAYAN_DATABASES="{
    'default':{
        'ENGINE':'django.db.backends.postgresql',
        'NAME':'$DB_NAME',
        'PASSWORD':'$DB_PASS',
        'USER':'$DB_USER',
        'HOST':'127.0.0.1'
    }
}"
export MAYAN_MEDIA_ROOT=$APP_DIR/media
EOF

service postgresql start

# Install mayan (pretty much) as per "basic deployment" from the "direct
# deployments" docs: https://docs.mayan-edms.com/chapters/deploying.html

su - $USER -c "$BIN/pip install --no-cache-dir -U pip"
su - $USER -c "$BIN/pip install --no-cache-dir $APP_NAME"
su - $USER -c "$BIN/pip install --no-cache-dir psycopg2==2.8.4 redis==3.4.1"
su - postgres -c "createuser $DB_USER"
su - postgres -c "createdb -O $DB_USER $DB_NAME"
su - postgres -c "psql postgres" <<EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py initialsetup"
su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py platformtemplate supervisord" \
    > $SV_CONF

#su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py makemigrations"
#su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py performupgrade"
#su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py collectstatic --noinput"

#sed -i "\|MAYAN_DATABASES|s|D: [0-9a-z]*,|D: $DB_PASS,|" $SV_CONF
echo 'LOGGING_LOG_FILE_PATH: /var/log/mayan/error.log' > $APP_DIR/media/config.yml
touch /var/log/mayan/error.log
chown mayan:mayan /var/log/mayan/error.log

# include mayan version in build log
installed_version=$(cat $APP_DIR/media/system/VERSION)

# tweak redis
REDIS_CONF=/etc/redis/redis.conf
echo "maxmemory-policy allkeys-lru" >> $REDIS_CONF
echo "save \"\"" >> $REDIS_CONF
echo "databases 2" >> $REDIS_CONF
echo "requirepass $RE_PASS" >> $REDIS_CONF

# update mayan admin password so "First time login" is never displayed
/usr/lib/inithooks/bin/mayan.py --email=admin@example.com --pass=$DB_PASS

service postgresql stop

# nginx config
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/mayan /etc/nginx/sites-enabled/mayan
ln -s /etc/adminer/nginx.conf /etc/nginx/sites-available/adminer
ln -s /etc/nginx/sites-available/adminer /etc/nginx/sites-enabled/adminer

# Configure fastcgi for Adminer via Nginx (php-fastcgi)
systemctl enable php-fastcgi
