#!/bin/bash -ex

# Set variables
#
DB_NAME=mayan
DB_USER=mayan
DB_PASS=$(mcookie)

APP_SETTINGS=/usr/share/mayan-edms/mayan/settings/local.py
APP_SETTINGS_TEMPLATE=/usr/share/mayan-edms/mayan/settings/db_settings.template

# Upgrade python-virtualenv:: (Not sure why, but virtualenv does not work until you upgrade it)
pip install --upgrade virtualenv

# Create application directory (virtualenv)
cd /usr/share
virtualenv mayan-edms


# Activate the environment 
source /usr/share/mayan-edms/bin/activate

# Install Mayan EDMS from PyPI
pip install mayan-edms

# Install the Python client for PostgreSQL, Redis, and uWSGI
pip install psycopg2 redis uwsgi

# Start postgresql server
/etc/init.d/postgresql start

# Create the database user and database for the installation
su postgres -c "createuser $DB_USER"
su postgres -c "createdb -O $DB_USER $DB_NAME"
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF


# Create log file directory for mayan and uwsgi
mkdir /var/log/mayan
mkdir /var/log/uwsgi

# Make a convenience symbolic link 
cd /usr/share/mayan-edms
ln -s lib/python2.7/site-packages/mayan .

# Make doc store in /srv
mkdir -p /srv/edms-data/document_storage

# Create an initial settings file and db.template
# We will recreate this on first boot, but create it
# here for testing builds.
mayan-edms.py createsettings -v 3

cat << EOF > $APP_SETTINGS_TEMPLATE
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '$DB_NAME',
        'USER': '$DB_USER',
        'PASSWORD': '$DB_PASS',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'

STORAGE_FILESTORAGE_LOCATION = '/srv/edms-data/document_storage'

EOF



# Create initial settings
mayan-edms.py createsettings

# Apply the settings template
cat $APP_SETTINGS_TEMPLATE >> $APP_SETTINGS


# Migrate the database or initialize the project
# TODO: If using a database with pre-config may want to 
# change this step to import database
mayan-edms.py initialsetup -v 3


# Disable the default NGINX site
rm /etc/nginx/sites-enabled/default

# Enable the NGINX site for Mayan EDMS
ln -s /etc/nginx/sites-available/mayan /etc/nginx/sites-enabled/

# Collect static files
mayan-edms.py collectstatic --noinput


# Make the installation and directory readable and writable by the webserver user
chown www-data:www-data /usr/share/mayan-edms -R
chown www-data:www-data /srv/edms-data -R


# Stop postgresql server
/etc/init.d/postgresql stop


# Link Nginx Adminer conifg
ln -s /etc/nginx/sites-available/adminer /etc/nginx/sites-enabled/adminer

# Configure fastcgi for Adminer via Nginx (php-fastcgi)
update-rc.d php-fastcgi defaults
