#!/bin/bash -e
# regenerate mayan django secert password

. /etc/default/inithooks

CONF=/usr/share/mayan-edms/mayan/settings/local.py
CONF_TEMPLATE=/usr/share/mayan-edms/mayan/settings/settings.template

# Stop services will be restarted when database password has been changed
supervisorctl stop all

# Remove settings file
rm $CONF

# Enter virtualenv
cd /usr/share/mayan-edms
source bin/activate

# Re-run createsettings 
mayan-edms.py createsettings

# Append template
cat $CONF_TEMPLATE >> $CONF

# Exit out of virtualenv
deactivate
