#!/bin/bash -e
# regenerate mayan pgsql password

. /etc/default/inithooks

SV_CONF=/etc/supervisor/conf.d/mayan.conf
RE_CONF=/etc/redis/redis.conf
ENV=/etc/mayan/env
DB_USER=mayan

# Create new passwords
DB_PASS=$(mcookie)
RE_PASS=$(mcookie)

# Update DB password in Supervisor config, as well as env file
sed -i "\|MAYAN_DATABASES|s|D: [0-9a-z]*,|D: $DB_PASS,|" $SV_CONF
sed -i "\|PASSWORD|s|:.*|:'$DB_PASS',|" $ENV

# Update the DB user password in postgres
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$DB_USER --pass="$DB_PASS"

# regen the Django secret
PYTHONPATH=/opt/mayan-edms/lib/python3.7/site-packages $INITHOOKS_PATH/bin/mayan-gen-secret.py

# Update Redis password
sed -i "s|redis.*@|redis://:${RE_PASS}@|" $SV_CONF
sed -i "\|^requirepass|s| .*| ${RE_PASS}|" $RE_CONF

# reload supervisor to ensure new db password is used
systemctl restart supervisor.service
systemctl restart redis-server.service
systemctl restart redis.service
