#!/bin/bash -e
# regenerate mayan pgsql password

. /etc/default/inithooks

CONF=/etc/supervisor/conf.d/mayan.conf
ENV=/etc/mayan/env
DB_USER=mayan

# Create new password
DB_PASS=$(mcookie)

# Set new password in config file, as well as env
for file in "$CONF $ENV"; do
    sed -i "\|MAYAN_DATABASE_PASSWORD|s|=.*|=$DB_PASS,|" $file
done

# Update the pastgres user password
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$DB_USER --pass="$DB_PASS"

# regen the Django secret
$INITHOOKS_PATH/bin/mayan-gen-secret.py

# reload Mayan
supervisorctl restart all
