#!/bin/bash -e
# regenerate mayan pgsql password

. /etc/default/inithooks

CONF=/usr/share/mayan-edms/mayan/settings/local.py
DB_USER=mayan

# Create new password
DB_PASS=$(mcookie)

# Set new password in config file
sed -i "s|'PASSWORD':.*|'PASSWORD': '$DB_PASS',|" $CONF


# Update the pastgres user password
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$DB_USER --pass="$DB_PASS"

# Since we reset the password, reload Mayan
supervisorctl restart all
