#!/bin/bash -e
# Set the super admin password/email for Mayan

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/mayan.py --pass="$APP_PASS" --email="$APP_EMAIL"


